### ISSUE TITLE
I use this extension, but it seems to have some bugs and can't be configured for ads.

### ISSUE THREAD

**Issue by shebaoting** [malago86/flarum-ads#1]
![](https://wyz.xyz/assets/files/2021-06-02/1622670444-953895-image.png)

**Comment by malago86** [comment]
Thanks for the report!

Can you check the last log file under public/storage and tell me if there is any error showing there related to this extension?

Thanks.

**Comment by shebaoting** [comment]
After I open the debug, I see a 404 error.
```
GET https://wyz.xyz/api/achievements

Flarum\Http\Exception\RouteNotFoundException: /achievements in /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php:58
Stack trace:
#0 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ResolveRoute->process()
#1 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#2 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process()
#3 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(56): Laminas\Stratigility\Next->handle()
#4 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#5 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#6 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process()
#7 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#8 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process()
#9 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#10 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process()
#11 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#12 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process()
#13 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#14 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process()
#15 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#16 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process()
#17 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#18 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\InjectActorReference->process()
#19 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#20 /www/wwwroot/wyz.xyz/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#21 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process()
#22 /www/wwwroot/wyz.xyz/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#23 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process()
#24 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle()
#25 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process()
#26 /www/wwwroot/wyz.xyz/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#27 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process()
#28 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#29 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ProcessIp->process()
#30 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle()
#31 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process()
#32 /www/wwwroot/wyz.xyz/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle()
#33 /www/wwwroot/wyz.xyz/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#34 /www/wwwroot/wyz.xyz/public/index.php(22): Flarum\Http\Server->listen()
#35 {main}
```

**Comment by Ralkage** [comment]
This error occurs when you don't have @malago86's Flarum Achievements installed as this fork is trying to [retrieve data](https://github.com/malago86/flarum-ads/blob/main/js/src/admin/components/AdsPage.js#L44) from the `/api/achievements` endpoint. This resource doesn't exist without the Achievements extension being installed which adds this specific endpoint.

Other tidbits:
1). https://github.com/malago86/flarum-ads/blob/main/src/Listeners/LoadSettingsFromDatabase.php should also be removed as you are already using the settings extender to add these settings.
2). You should work on completely changing the namespace from Flagrow to your specific namespace since you already started to do that in some places.
3). I would also suggest using the Flarum CLI to update all of the JS imports for Flarum in one go 😁

**Comment by malago86** [comment]
Oh no... I don't know why I left those lines of code there... They obviously don't belong to this extension! 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️

I plan to update the namespace in the future when I do more changes. For now I just wanted to get it out since people seemed to be interested.

@shebaoting You can update to 0.3.1, it should fix this error
